# Generated by Django 3.1.4 on 2025-04-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250409_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('producer', 'E-Waste Producer'), ('collector', 'Collector & Recycler')], default='producer', max_length=10),
        ),
    ]
