# Generated by Django 3.1.4 on 2025-04-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250410_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='actual_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='final_disposition',
            field=models.CharField(blank=True, choices=[('recycled', 'Recycled'), ('landfill', 'Sent to Landfill'), ('other', 'Other Disposition')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='recycling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='recycling_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('recycled', 'Recycled'), ('landfill', 'Sent to Landfill'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
